version: '3.8'

services:
  # 1. Mesin Redis
  redis-cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 2. Mesin Backend API lo
  homs-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis-cache:6379/0
      # Taruh env var lainnya di sini atau link ke file .env
    depends_on:
      - redis-cache